### ISSUE TITLE
Corrigir o cadastro de Contas Contábeis 

### ISSUE THREAD

**Issue by julianocgil** [andrevilmo/proemp#15]
Corrigir o cadastro de Contas Contábeis,

Exemplificando o que são contas contábeis.
CC - São como Caixas que guardam os lançamentos (papeis) dentro.

A conta do Banco é o espaço..   quem tem os lançamentos de entrada e saída dentro.
Apesar da caixa, com "Conta de luz", ter apenas lançamentos de Faturas da luz.. Estes dois itens têm que estar separados, pq por exemplo, pode parecer uma segunda fatura de luz, que deve ficar na mesma caixa. (Uma conta --para--  Muitas fatura/lançamentos)

segue o banco de dados, que vai dar certo

**Comment by andrevilmo** [comment]
Removidos os campos da conta em tela
