### ISSUE TITLE
Configurar o thema para os graficos

### ISSUE THREAD

**Issue by julianocgil** [andrevilmo/proemp#3]
A exportação do arquivo jasper tem que ser feita depois da associação arquivo de "thema.jar" no "Reference Libraries"

**Comment by andrevilmo** [comment]
Melhorar a disposição das colunas: deixar colunas mais juntas e colocar legenda nos linhas como de percentual de lucro no relatorio de venda mensal

**Comment by julianocgil** [comment]
Thema e Customizer adicionados.
